Tweak configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -64,16 +64,15 @@ CXXFLAGS=$(${R_HOME}/bin/R CMD config CXXFLAGS)
 CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
 
 # Test for ffmpeg
-tmpfile=$(mktemp)
-echo "#include $PKG_TEST_HEADER" | ${CXX} -E ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ - >/dev/null 2>$tmpfile
+echo "#include $PKG_TEST_HEADER" | ${CXX} -E ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ - >/dev/null 2>configure.log
 if [ $? -ne 0 ]; then
-  echo "------------------------- ANTICONF ERROR ---------------------------"
-  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
+  echo "-----------------------------[ ANTICONF ]----------------------------------"
+  echo "Configuration failed to find the $PKG_CONFIG_NAME library. Try installing:"
   echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu 18.04 and up)"
   echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
   echo " * csw: $PKG_CSW_NAME (Solaris)"
   echo " * brew: $PKG_BREW_NAME (MacOS)"
-  echo "For Ubuntu versions Trusty (14.04) and Xenial (16.04) use this PPA:"
+  echo "For Ubuntu Trusty (14.04) and Xenial (16.04) use this PPA:"
   echo "   sudo add-apt-repository -y ppa:cran/ffmpeg-3"
   echo "   sudo apt-get update"
   echo "   sudo apt-get install -y $PKG_DEB_NAME"
@@ -81,9 +80,10 @@ if [ $? -ne 0 ]; then
   echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
   echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
   echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-  echo "--------------------------------------------------------------------"
-  cat $tmpfile
-  exit 1;
+  echo "---------------------------[ ERROR MESSAGE ]--------------------------------"
+  cat configure.log
+  echo "----------------------------------------------------------------------------"
+  exit 1
 fi
 
 # Write to Makevars
