Update NEWS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,7 +17,7 @@ PKG_LIBS="-lavfilter"
 # Detect too old ffmpeg
 pkg-config ${PKG_CONFIG_NAME} --max-version=5.99 2>/dev/null
 if [ $? -eq 0 ]; then
-  echo "Your version of FFmpeg is too old! Need at least FFmpeg (>= 3.2)"
+  echo "ERROR: Your version of FFmpeg is too old! Need at least FFmpeg (>= 3.2)" 1>&2
   exit 1
 fi
 
